### ISSUE TITLE
[1.20.1] Client Crash on startup

### ISSUE THREAD

**Issue by KLONOA9X6** [txnimc/BalancedFlight#15]
Game without this mod will startup normally.
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-07-22 19:45:49
Description: Initializing game

java.lang.IllegalAccessError: class me.shedaniel.rei.impl.client.CodepointMapWrapper tried to access private field net.minecraft.client.gui.font.CodepointMap.f_283773_ (me.shedaniel.rei.impl.client.CodepointMapWrapper is in module roughlyenoughitems@12.0.634 of loader 'TRANSFORMER' @566f1852; net.minecraft.client.gui.font.CodepointMap is in module minecraft@1.20.1 of loader 'TRANSFORMER' @566f1852)
	at me.shedaniel.rei.impl.client.CodepointMapWrapper.<init>(CodepointMapWrapper.java:37) ~[RoughlyEnoughItems-12.0.634.jar%23262!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.gui.font.FontSet.handler$bag000$init(FontSet.java:557) ~[client-1.20.1-20230612.114412-srg.jar%23276!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rei.mixins.json:MixinFontSet,pl:mixin:A}
	at net.minecraft.client.gui.font.FontSet.<init>(FontSet.java:43) ~[client-1.20.1-20230612.114412-srg.jar%23276!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rei.mixins.json:MixinFontSet,pl:mixin:A}
	at net.minecraft.client.gui.font.FontManager.<init>(FontManager.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23276!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.modernui-textmc.json:AccessFontManager,pl:mixin:APP:mixins.modernui-textmc.json:MixinFontManager,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:475) ~[client-1.20.1-20230612.114412-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.rei.impl.client.CodepointMapWrapper.<init>(CodepointMapWrapper.java:37) ~[RoughlyEnoughItems-12.0.634.jar%23262!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.gui.font.FontSet.handler$bag000$init(FontSet.java:557) ~[client-1.20.1-20230612.114412-srg.jar%23276!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rei.mixins.json:MixinFontSet,pl:mixin:A}
	at net.minecraft.client.gui.font.FontSet.<init>(FontSet.java:43) ~[client-1.20.1-20230612.114412-srg.jar%23276!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rei.mixins.json:MixinFontSet,pl:mixin:A}
	at net.minecraft.client.gui.font.FontManager.<init>(FontManager.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23276!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.modernui-textmc.json:AccessFontManager,pl:mixin:APP:mixins.modernui-textmc.json:MixinFontManager,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:475) ~[client-1.20.1-20230612.114412-srg.jar%23276!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
		AcGenral.DLL:Windows Compatibility DLL:10.0.22621.1928 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:用户体验控件库:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:加密 API32:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.DLL:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ControlLib.dll:Intel Graphics Control Lib Loader for Intel Graphics:1.0.104:
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.1635:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS 客户端 API DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.1778 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL 实用工具库 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP 帮助程序 API:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		IntelControlLib.dll:Intel Graphics Control Lib Runtime:1.0.104:
		KERNEL32.DLL:Windows NT 基本 API 客户端 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT 基本 API 客户端 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		MPR.dll:多提供程序路由器 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF 服务器 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		MessageBus.dll:NVIDIA Message Bus::NVIDIA Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.1992 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.21.1:
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:远程过程调用运行时:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		SETUPAPI.dll:Windows 安装程序 API:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell 公用 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		SHLWAPI.dll:外壳简易实用工具库:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		SspiCli.dll:Security Support Provider Interface:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:多用户 Windows 用户 API 客户端 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP 服务:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.1928 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32 位 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		advapi32.dll:高级 Windows 32 基本 API:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:应用程序兼容性客户端库:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows 加密基元库:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.1928 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:用于 Windows 的 Microsoft COM:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		cryptnet.dll:Crypto Network Related API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		d3d11.dll:Direct3D 11 Runtime:10.0.22621.1928 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dcomp.dll:Microsoft DirectComposition Library:10.0.22621.1928 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP 客户端服务:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 客户端:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		directxdatabasehelper.dll:DirectXDatabaseHelper:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
		drvstore.dll:Driver Store API:10.0.22621.1778 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft 桌面窗口管理器 API:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.22621.1778 (WinBuild.160101.0800):Microsoft Corporation
		dxgi.dll:DirectX Graphics Infrastructure:10.0.22621.1485 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec 用户模式 API:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.1778 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		igc64.dll:Intel Graphics Shader Compiler for Intel(R) Graphics Accelerator:31.0.101.3358:Intel Corporation
		igd10iumd64.dll:User Mode Driver for Intel(R) Graphics Technology:31.0.101.3358:Intel Corporation
		igd10um64xe.DLL:User Mode Driver for Intel(R) Graphics Technology:31.0.101.3358:Intel Corporation
		igdgmm64.dll:User Mode Driver for Intel(R) Graphics Technology:31.0.101.3358:Intel Corporation
		imagehlp.dll:Windows NT Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		instrument.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		java.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		java.exe:OpenJDK Platform binary:17.0.4.1:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		jna12487054728647118243.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.4.1:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		mdnsNSP.dll:Bonjour Namespace Provider:3,0,0,10:Apple Inc.
		msasn1.dll:ASN.1 Runtime APIs:10.0.22621.819 (WinBuild.160101.0800):Microsoft Corporation
		mscms.dll:Microsoft 颜色匹配系统 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 服务提供程序:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:电子邮件命名填充提供程序:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT 层 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA 提供程序:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		nvapi64.dll:NVIDIA NVAPI Library, Version 536.23 :31.0.15.3623:NVIDIA Corporation
		nvldumdx.dll:NVIDIA Driver Loader, Version 536.23 :31.0.15.3623:NVIDIA Corporation
		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:31.0.15.3623:NVIDIA Corporation
		nvspcap64.dll:NVIDIA Game Proxy:3.27.0.112:NVIDIA Corporation
		nvwgf2umx.dll:NVIDIA D3D10 Driver, Version 536.23 :31.0.15.3623:NVIDIA Corporation
		ole32.dll:用于 Windows 的 Microsoft OLE:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		opengl32.dll:OpenGL Client DLL:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
		pdh.dll:Windows 性能数据助手 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows 系统性能对象 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		perfproc.dll:Windows 系统进程性能对象 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP 命名空间提供程序:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:电源配置文件帮助程序 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.1928 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shcore.dll:SHCORE:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22621.1928 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme 库:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
		win32u.dll:Win32u:10.0.22621.1992 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows 基本类型 DLL:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		wldp.dll:Windows 锁定策略:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.1778 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft 公共控制器 API:10.0.22621.1927 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.4.1:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.4.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 425444192 bytes (405 MiB) / 905969664 bytes (864 MiB) up to 9428795392 bytes (8992 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12500H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3050 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x25a2
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Graphics card #1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x46a6
	Graphics card #1 versionInfo: DriverVersion=31.0.101.3358
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 48344.49
	Virtual memory used (MB): 16961.83
	Swap memory total (MB): 15872.00
	Swap memory used (MB): 189.50
	JVM Flags: 11 total; -Xmx8988m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 16x 12th Gen Intel(R) Core(TM) i5-12500H
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@4.3.0
		lowcodefml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.1.1-universal.jar                 |Forge                         |forge                         |47.1.1              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
```

**Comment by KLONOA9X6** [comment]
Modlist:
```
ad_astra-forge-1.20.1-1.15.1.jar
appleskin-forge-mc1.20.1-2.5.0.jar
architectury-9.0.8-forge.jar
AttributeFix-Forge-1.20.1-21.0.1.jar
balancedflight-1.20.1_v2.1.0.jar
BetterPvP_23.5.0_Forge_1.20.jar
BetterThirdPerson-Forge-1.20-1.9.0.jar
botarium-forge-1.20-2.1.0.jar
canary-mc1.20(.1)-0.2.6.jar
cfm-forge-1.20.1-7.0.0-pre36.jar
cloth-config-11.0.99-forge.jar
create-1.20.1-0.5.1.d.jar
createdieselgenerators-1.20.1-1.1b.jar
createoreexcavation-1.20-1.3.0.jar
create_jetpack-forge-4.0.1.jar
curios-forge-5.2.0-beta.3+1.20.1.jar
dynamiclightsreforged-1.20.1_v1.5.0.jar
FarmersDelight-1.20.1-1.2.2a.jar
ferritecore-6.0.0-forge.jar
Forgematica-0.1.0-mc1.20.1.jar
IMBlocker.jar
InventoryProfilesNext-forge-1.20-1.10.6.jar
Jade-1.20-forge-11.1.4.jar
JadeAddons-1.20.1-forge-5.1.0.jar
kotlinforforge-4.3.0-all.jar
l2artifacts-2.4.5.jar
l2complements-2.4.10.jar
l2library-2.4.14.jar
l2weaponry-2.4.8.jar
libIPN-forge-1.20-3.0.2.jar
MaFgLib-0.1.2-mc1.20.1.jar
MaxHealthFix-Forge-1.20.1-12.0.1.jar
mcw-bridges-2.1.1-mc1.20.1forge.jar
mcw-doors-1.1.0forge-mc1.20.1.jar
mcw-fences-1.0.7-mc1.20.1forge.jar
mcw-lights-1.0.6-mc1.20.1forge.jar
mcw-paths-1.0.3forge-mc1.20.1.jar
mcw-roofs-2.2.4-mc1.20.1forge.jar
mcw-trapdoors-1.1.1-mc1.20.1forge.jar
memoryleakfix-forge-1.17+-1.1.1.jar
ModernUI-1.20.1-3.7.1.3-universal.jar
moonlight-1.20-2.6.0-forge.jar
nvidium-0.1.13-alpha.jar
REIPluginCompatibilities-forge-12.0.55.jar
resourcefulconfig-forge-1.20-2.0.0.jar
resourcefullib-forge-1.20.1-2.1.1.jar
RoughlyEnoughItems-12.0.634.jar
rubidium-0.6.5.jar
rubidium_extras-1.20.1_v1.4.3.jar
supplementaries-1.20-2.5.18.jar
Terralith_1.20.1_v2.4.2.jar
TextruesRubidiumOptions-1.0.0+mc1.20.jar
toms_storage-1.20-1.6.4.jar
TravelersBackpack-1.20.1-9.1.4.jar
Tweakerge-0.1.0-mc1.20.1.jar
twilightdelight-2.0.1.jar
twilightforest-1.20.1-4.3.1740-universal.jar
voicechat-forge-1.20.1-2.4.14.jar
XaerosWorldMap_1.30.6_Forge_1.20.jar
yesstevemodel-1.20-release-1.1.5.jar
```

**Comment by KLONOA9X6** [comment]
Oops, I forgot to install Geckolib. Sorry.
