### ISSUE TITLE
Update to create 0.5.1.e

### ISSUE THREAD

**Issue by ghost** [txnimc/BalancedFlight#23]
Hello,
Create has launched a new version, and it breaks a lot of add-ons, including this one.
Could you fix it ?

Here the logs 

```
[21/09/2023 23:22:04 PM] Caused by: java.lang.NoSuchFieldError: MAIN_TAB
[21/09/2023 23:22:04 PM] 	at TRANSFORMER/balancedflight@1.20.1_v2.1.0/com.vice.balancedflight.AllBlocks.<clinit>(AllBlocks.java:11)
[21/09/2023 23:22:04 PM] 	at TRANSFORMER/balancedflight@1.20.1_v2.1.0/com.vice.balancedflight.BalancedFlight.<init>(BalancedFlight.java:54)
[21/09/2023 23:22:04 PM] 	... 14 more
[21/09/2023 23:22:04 PM] [modloading-worker-0/ERROR] Failed to create mod instance. ModID: balancedflight, class com.vice.balancedflight.BalancedFlight
[21/09/2023 23:22:04 PM] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21/09/2023 23:22:04 PM] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[21/09/2023 23:22:04 PM] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21/09/2023 23:22:04 PM] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[21/09/2023 23:22:04 PM] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[21/09/2023 23:22:04 PM] 	at LAYER PLUGIN/javafmllanguage@1.20.1-47.1.47/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68)
[21/09/2023 23:22:04 PM] 	at LAYER PLUGIN/fmlcore@1.20.1-47.1.47/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123)
[21/09/2023 23:22:04 PM] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[21/09/2023 23:22:04 PM] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[21/09/2023 23:22:04 PM] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21/09/2023 23:22:04 PM] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21/09/2023 23:22:04 PM] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21/09/2023 23:22:04 PM] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21/09/2023 23:22:04 PM] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Fundryi** [comment]
Neeed this update :o

**Comment by billjk2013** [comment]
yes an update would be much appreciated

**Comment by Fundryi** [comment]
@nthxny 
https://github.com/anthxnymc/BalancedFlight/pull/24
